### ISSUE TITLE
Use webRTC audio as inputs

### ISSUE THREAD

**Issue by mgw-sbic** [jamesfiltness/web-audio-mixer#5]
Hi James, Just wondering if it is possible to use webRTC audio streams with your mixer somehow?

Thank you!

**Comment by nkev** [comment]
I think that would not be possible without complicating it because you would have to ensure the streams are in sync as they come in.

**Comment by mgw-sbic** [comment]
Hey, we are handling the syncing ourselves already. we just need a way to mix audio in the cloud.

**Comment by jamesfiltness** [comment]
Hi Michael, There seem to be some methods available in the Web Audio API which enable working with WebRTC (https://dvcs.w3.org/hg/audio/raw-file/tip/webaudio/webrtc-integration.html). Currently this mixer works by first buffering all of the audio tracks in the **Daw** class before initalising the **Mixer** class. You'd need to do a lot of refactoring in the **Mixer** clas to get this working with the code as it is. I'm think this is possible but I'd be starting from scratch if I were trying to achieve this.

**Comment by mgw-sbic** [comment]
Hi James! I see. we are looking for audio mixing in the cloud, and so far have not found anything solid. We don't really have time to do the development ourselves giving some time constraints. Thank you so much for responding here! I hope you and your family are safe in these crazy times.
