### ISSUE TITLE
BUILD

### ISSUE THREAD

**Issue by cbelda** [jamesfiltness/web-audio-mixer#6]
Hi! Nice app man :)

I was trying something in my fork and wanted to ask you how do you build this for prod.

Thanks a lot,
Cris

**Comment by jamesfiltness** [comment]
Hi Cris,

Thanks :)

There is no build for this project - it's just all static assets. The (example)[https://jamesfiltness.github.io/web-audio-mixer/] just runs on github pages. The branch for github pages is here: https://github.com/jamesfiltness/web-audio-mixer/blob/gh-pages/index.html 

If you look in (index.html)[https://github.com/jamesfiltness/web-audio-mixer/blob/gh-pages/index.html] you can see that `mixer.js` is referenced. All of the mp3s are also hosted in github pages.

`mixer.js` uses jQuery to hook in to a div with an id of `mixer` defined in `index.html`. 

I always planned to run it on github pages so kept it simple. There is a node server included but only for the purposes of running the project locally during development. There are details about that in the README.

Hope that helps.
